import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { css } from "@stitches/react";

const button = css({
  appearance: "none",
  border: "none",
  padding: "10px 20px",
  borderRadius: "20px",
  color: "white",

  variants: {
    variant: {
      primary: {
        backgroundColor: "mediumpurple",
        "&:hover": {
          backgroundColor: "indigo",
        },
      },
      dark: {
        backgroundColor: "black",
        "&:hover": {
          backgroundColor: "dimgray",
        },
      },
    },
    outlined: {
      true: {
        border: "2px solid pink",
        backgroundColor: "transparent",
      },
    },
  },

  compoundVariants: [
    {
      variant: "primary",
      outlined: true,
      css: {
        color: "mediumpurple",
        borderColor: "mediumpurple",
        "&:hover": {
          color: "white",
        },
      },
    },
    {
      variant: "dark",
      outlined: true,
      css: {
        color: "black",
        borderColor: "black",
      },
    },
  ],
  defaultVariants: {
    variant: "primary",
  },
});

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button className={button()}>Button</button>
        <br></br>
        <button className={button({ variant: "dark" })}>Button</button>
        <br></br>
        <button className={button({ outlined: true })}>Button Outlined</button>
        <br></br>
        <button className={button({ variant: "dark", outlined: true })}>
          Button Dark Outlined
        </button>
      </main>
    </div>
  );
};

export default Home;
