import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { css, createStitches } from "@stitches/react";

//base tokens
//theme with createStitches -> css variables <3
const { css } = createStitches({
  theme: {
    colors: {
      basePurple: "mediumpurple",
      darkPurple: "indigo",
      black: "black",
      white: "white",
      gray: "dimgray",
    },
    fontSizes: {
      small: "13px",
      medium: "18px",
    },
    space: {
      1: "5px",
      2: "10px",
      3: "15px",
      4: "20px",
    },
    radii: {
      round: "20px",
    },
  },
});

const button = css({
  appearance: "none",
  border: "none",
  padding: "$2 $4",
  borderRadius: "$round",
  color: "$white",

  variants: {
    size: {
      small: { fontSize: 13 },
      medium: { fontSize: 18 },
    },
    variant: {
      primary: {
        backgroundColor: "$basePurple",
        "&:hover": {
          backgroundColor: "$darkPurple",
        },
      },
      dark: {
        backgroundColor: "$black",
        "&:hover": {
          backgroundColor: "$gray",
        },
      },
    },
    outlined: {
      true: {
        border: "2px solid",
        backgroundColor: "transparent",
      },
    },
  },

  compoundVariants: [
    {
      variant: "primary",
      outlined: true,
      css: {
        color: "$basePurple",
        borderColor: "$basePurple",
        "&:hover": {
          color: "$white",
        },
      },
    },
    {
      variant: "dark",
      outlined: true,
      css: {
        color: "$black",
        borderColor: "$black",
      },
    },
  ],
  defaultVariants: {
    variant: "primary",
    size: "$small",
  },
});

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>stitches</h1>
        <div>
          <section className={styles.section}>
            <button className={button()}>Button</button>

            <button className={button({ variant: "dark" })}>Button</button>

            <button className={button({ outlined: true })}>
              Button Outlined
            </button>

            <button className={button({ variant: "dark", outlined: true })}>
              Button Dark Outlined
            </button>
          </section>

          <hr />

          <section className={styles.section}>
            <button className={button({ size: "$small" })}>
              Button size small
            </button>

            <button
              className={button({
                size: {
                  "@initial": "$small",
                  "@media (min-width: 500px)": "$medium",
                },
              })}
            >
              Responsive Button
            </button>
          </section>
        </div>
      </main>
    </div>
  );
};

export default Home;
